(function(d){function e(){}function o(c){A=[c]}function q(c,g,h,p){try{p=c&&c.apply(g.context||g,h)}catch(B){p=false}return p}function C(c){return/\?/.test(c)?"&":"?"}function L(c){function g(j){M++||(N(),O&&(D[i]={s:[j]}),B&&(j=B.apply(c,[j])),q(c.success,c,[j,x]),q(p,c,[c,x]))}function h(j){M++||(N(),O&&j!=E&&(D[i]=j),q(c.error,c,[c,j]),q(p,c,[c,j]))}c=d.extend({},a,c);var p=c.complete,B=c.dataFilter,k=c.callbackParameter,F=c.callback,n=c.cache,O=c.pageCache,V=c.charset,i=c.url,t=c.data,W=c.timeout,
P,M=0,N=e,f,G,T;return c.abort=function(){!M++&&N()},q(c.beforeSend,c,[c])===false||M?c:(i=i||u,t=t?typeof t=="string"?t:d.param(t,c.traditional):u,i+=t?C(i)+t:u,k&&(i+=C(i)+encodeURIComponent(k)+"=?"),!n&&!O&&(i+=C(i)+"_"+(new Date).getTime()+"="),i=i.replace(/=\?(&|$)/,"="+F+"$1"),O&&(P=D[i])?P.s?g(P.s[0]):h(P):(y[F]=o,f=d(r)[0],f.id=v+U++,V&&(f[H]=V),b&&b.version()<11.6?((G=d(r)[0]).text="document.getElementById('"+f.id+"')."+z+"()"):(f[Q]=Q),!(I in f)&&J in f&&(f.htmlFor=f.id,f.event=w),f[I]=
f[z]=f[J]=function(j){if(!f[l]||/loaded|complete/.test(f[l])){try{f[w]&&f[w]()}catch(X){}j=A;A=0;j?g(j[0]):h(K)}},f.src=i,N=function(){T&&clearTimeout(T);f[J]=f[I]=f[z]=null;s[m](f);G&&s[m](G)},s[R](f,S),G&&s[R](G,S),T=W>0&&setTimeout(function(){h(E)},W)),c)}var Q="async",H="charset",u="",K="error",R="insertBefore",v="_jqjsp",w="onclick",z="on"+K,I="onload",J="onreadystatechange",l="readyState",m="removeChild",r="<script>",x="success",E="timeout",y=window,s=d("head")[0]||document.documentElement,
S=s.firstChild,D={},U=0,A,a={callback:v,url:location.href},b=y.opera;L.setup=function(c){d.extend(a,c)};d.jsonp=L})(jQuery);var suggestionsearch_enable=function(){jQuery("#navbar-query").searchAutocomplete({maxResults:6,alwaysScrollIntoView:false,resultsDiv:jQuery("#navbar-suggestionsearch"),keyboardControl:true});jQuery("#navbar-query").attr("autocomplete","off");repositionSuggestionSearch()},repositionSuggestionSearch=function(){var d=jQuery("#navbar-query"),e=d.position(),o=d.width();d=d.height();jQuery("#navbar-suggestionsearch").css({left:e.left+0+"px",top:e.top+d+11+"px",width:o+115+"px"})},suggestionsearch_disable=
function(){jQuery("#navbar-query").stopSearchAutocomplete({resultsDiv:jQuery("#navbar-suggestionsearch")});jQuery("#navbar-query").attr("autocomplete","on")},suggestionsearch_dropdown_choice=function(d){"all"==d.value?suggestionsearch_enable():suggestionsearch_disable()};function trackAndClick(d,e,o){(new Image).src="/rg/"+d+"/"+e+"/images/b.gif";setTimeout(function(){document.location=o.href},0);return false}
jQuery(document).ready(function(){var d=jQuery('#nb_search select[name="s"]');if(d.length>0){d=d[0];suggestionsearch_dropdown_choice(d)}});
(function(d){d.fn.searchAutocomplete=function(e){function o(a){q();jQuery(a).addClass("highlighted")}function q(){m.find("a.highlighted").removeClass("highlighted")}function C(){var a=m.find("a.highlighted");a.length>0?a.first().get(0).click():jQuery("#navbar-form").submit()}function L(){if(m.find("a").length>0){var a=m.find("a.highlighted");if(a.length>0){a=a.first();var b=a.prev("a");b.length>0&&b.first().addClass("highlighted");a.removeClass("highlighted")}}}function Q(){var a=m.find("a");if(a.length>
0){var b=m.find("a.highlighted");if(b.length>0){a=b.first();b=a.next("a");if(b.length>0){b.first().addClass("highlighted");a.removeClass("highlighted")}}else a.first().addClass("highlighted")}}function H(){repositionSuggestionSearch();m.css("display","block")}function u(){m.css("display","none")}function K(a){if(a){a=a.toLowerCase();if(a.length>20)a=a.substr(0,20);a=a.replace(/^\s*/,"").replace(/[ ]+/g,"_");if(U.test(a))a=a.replace(/[\u00e0\u00c0\u00e1\u00c1\u00e2\u00c2\u00e3\u00c3\u00e4\u00c4\u00e5\u00c5\u00e6\u00c6]/g,
"a").replace(/[\u00e7\u00c7]/g,"c").replace(/[\u00e8\u00c8\u00e9\u00c9\u00ea\u00ca\u00eb\u00cb]/g,"e").replace(/[\u00ec\u00cd\u00ed\u00cd\u00ee\u00ce\u00ef\u00cf]/g,"i").replace(/[\u00f0\u00d0]/g,"d").replace(/[\u00f1\u00d1]/g,"n").replace(/[\u00f2\u00d2\u00f3\u00d3\u00f4\u00d4\u00f5\u00d5\u00f6\u00d6\u00f8\u00d8]/g,"o").replace(/[\u00f9\u00d9\u00fa\u00da\u00fb\u00db\u00fc\u00dc]/g,"u").replace(/[\u00fd\u00dd\u00ff]/g,"y").replace(/[\u00fe\u00de]/g,"t").replace(/[\u00df]/g,"ss");return a=a.replace(/[\W]/g,
"")}return""}function R(){w(l.val())}function v(a,b){if(a&&b&&b.length<=a.length&&a.substr(0,b.length)===b)return true;return false}function w(a){var b=K(a);if(b.length==0){u();E=x=r=""}else if(b!==r){H();d.jsonp({charset:"UTF-8",dataType:"jsonp",callback:"imdb$"+b,url:"http://sg.media-imdb.com/suggests/"+b.substr(0,1)+"/"+b+".json",error:function(c,g){if(g==="error"&&b.length>1){E=b;v(r,x)?I(b):w(b.substr(0,b.length-1))}},success:function(c){z(c,b);x=b;y=c},pageCache:pageCacheSetting});r=b}}function z(a,
b){if(r===b){var c=b="";if(typeof d("#nb_search").attr("data-hostname")!="undefined")c="http://"+d("#nb_search").attr("data-hostname");for(var g=0;g<a.d.length&&g<S;g+=1){var h=a.d[g],p="";if(d("#megaMenu").length)p="nv_";var B=p+"sr_"+(g+1),k=h.id,F="film-40x54.png",n;if(v(k,"nm")){n=c+"/name/"+k+"/";F="people-40x54.png"}else if(v(k,"tt"))n=c+"/title/"+k+"/";else if(v(k,"http://"))n=k;if(n){k={url:n,title:h.l,detail:h.s,placeholder:F};if(h.i)k.img={url:h.i[0].replace("._V1_.jpg","._V1._SX40_CR0,0,40,54_.jpg"),
width:40,height:54};if(h.y)k.extra="("+h.y+")";b+=J(k,B)}}if(b.length>0){H();n=l.val();a=n.replace(D," ");n=jQuery("<div/>").text(n).html();b+='<a class="moreResults" href="';b+=c+"/find?s=all&q="+a+"&ref_="+p+'sr_sm">';b+='<span class="message">See all results for "<span class="query">'+n+'</span>"</span>&nbsp;<span class="raquo">&raquo;</span>';b+="</a>";m.html(b);m.find("a").hover(function(){o(this)},function(){})}}}function I(a){for(var b=[],c=[],g=0;g<y.d.length;g+=1){var h=y.d[g];K(h.l).match(a)?
b.push(h):c.push(h)}z({d:b.concat(c)},a)}function J(a,b){b='<a href="'+a.url+"?ref_="+b+'" class="poster"';b+=">";if(a.img){b+='<img src="'+a.img.url+'"';b+=" style=\"background:url('http://i.media-imdb.com/images/mobile/"+a.placeholder+"')\"";if(a.img.width&&a.img.height)b+=' width="'+a.img.width+'" height="'+a.img.height+'"';b+=">"}else if(a.placeholder)b+='<img src="http://i.media-imdb.com/images/mobile/'+a.placeholder+'">';b+='<div class="suggestionlabel">';b+='<span class="title">'+a.title+"</span>";
if(a.extra)b+=' <span class="extra">'+a.extra+"</span>";if(a.detail)b+='<div class="detail">'+a.detail+"</div>";b+="</div></a>";return b}if(typeof e=="undefined")e={};var l=jQuery(this),m="resultsDiv"in e?e.resultsDiv:jQuery("#autocomplete"),r="",x="",E="",y="",s,S="maxResults"in e?e.maxResults:3,D=/[^\w\u00e0\u00c0\u00e1\u00c1\u00e2\u00c2\u00e3\u00c3\u00e4\u00c4\u00e5\u00c5\u00e6\u00c6\u00e7\u00c7\u00e8\u00c8\u00e9\u00c9\u00ea\u00ca\u00eb\u00cb\u00ec\u00cd\u00ed\u00cd\u00ee\u00ce\u00ef\u00cf\u00f0\u00d0\u00f1\u00d1\u00f2\u00d2\u00f3\u00d3\u00f4\u00d4\u00f5\u00d5\u00f6\u00d6\u00f8\u00d8\u00f9\u00d9\u00fa\u00da\u00fb\u00db\u00fc\u00dc\u00fd\u00dd\u00ff\u00fe\u00de\u00df]/g,
U=/[\u00e0\u00c0\u00e1\u00c1\u00e2\u00c2\u00e3\u00c3\u00e4\u00c4\u00e5\u00c5\u00e6\u00c6\u00e7\u00c7\u00e8\u00c8\u00e9\u00c9\u00ea\u00ca\u00eb\u00cb\u00ec\u00cd\u00ed\u00cd\u00ee\u00ce\u00ef\u00cf\u00f0\u00d0\u00f1\u00d1\u00f2\u00d2\u00f3\u00d3\u00f4\u00d4\u00f5\u00d5\u00f6\u00d6\u00f8\u00d8\u00f9\u00d9\u00fa\u00da\u00fb\u00db\u00fc\u00dc\u00fd\u00dd\u00ff\u00fe\u00de\u00df]/,A="keyboardControl"in e?e.keyboardControl:false;alwaysScrollIntoView="alwaysScrollIntoView"in e?e.alwaysScrollIntoView:true;
pageCacheSetting=d.browser.msie==true?false:true;l.focus(function(){alwaysScrollIntoView&&this.scrollIntoView();if(l.val().length>0){w(l.val());H()}});l.blur(function(){s=setTimeout(u,300)});l.keydown(function(a){if(A)if(a.keyCode==38){l.focus();L();return false}else if(a.keyCode==40){l.focus();Q();return false}else if(a.keyCode==13){C();return false}else if(a.keyCode==27){q();u();return false}l.focus();s=setTimeout(R,0)})};d.fn.stopSearchAutocomplete=function(e){if(typeof e=="undefined")e={};var o=
jQuery(this);e="resultsDiv"in e?e.resultsDiv:jQuery("#autocomplete");o.unbind("focus");o.unbind("blur");o.unbind("keydown");e.css("display","none")}})(jQuery);
